name: projekaganebey
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  motion_tab_bar: ^2.0.4
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  flutter_pin_code_fields: ^2.2.0
  persistent_bottom_nav_bar: ^6.2.1
  google_fonts: ^6.2.1
  toggle_switch: ^2.3.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  fluttertoast: ^8.2.8
  firebase_storage: ^12.3.6
  turkish: ^0.2.1
  number_paginator: ^0.4.1
  intl: ^0.20.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2 # flutter_launcher_icons dev_dependencies'e taşındı

flutter_icons:
  android: true
  ios: true
  image_path: "assets/daire.png" # Kullanılacak simge yolu

flutter:
  uses-material-design: true
  assets:
    - assets/ # Tüm assets klasörünü dahil ettik
